-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 09:54:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema transactions
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `transactions` ;

-- -----------------------------------------------------
-- Schema transactions
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `transactions` DEFAULT CHARACTER SET utf8 ;
-- USE `transactions` ;

-- -----------------------------------------------------
-- Table `transactions`.`transaction_status`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `transactions`.`transaction_status` ;

CREATE TABLE IF NOT EXISTS transactions.transaction_status (
  id int NOT NULL AUTO_INCREMENT,
  identifier VARCHAR(36),
  file_name VARCHAR(90),
  file_size FLOAT,
  status VARCHAR(45),
  PRIMARY KEY (id))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
