--
-- Variantstore PostgreSQL transaction database
--

SET SCHEMA 'transactions';

--
-- Name: transaction_status; Type: TABLE; Schema: transactions;
--

CREATE TABLE transactions.transaction_status (
                         id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
                         identifier character varying,
                         file_name character varying,
                         file_size float,
                         status character varying
);

--
-- Name: transaction_status transaction_status_pkey; Type: CONSTRAINT; Schema: transactions;
--

ALTER TABLE ONLY transactions.transaction_status
    ADD CONSTRAINT transaction_status_pkey PRIMARY KEY (id);
