# # This workflow runs all available tests and builds the .jar files
name: Varianstore CI (compile, test, package)

# Trigger the workflow on push and pull request activity
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # set up JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # maven repository caching
      - name: Load local Maven repository cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # build with maven and run tests
      - name: Build with Maven and run tests
        run: mvn --batch-mode verify
