# # This workflow runs all available tests and builds the .jar files
name: Varianstore CI

# Trigger the workflow on push and pull request activity
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # maven repository caching
      - name: Load local Maven repository cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # build with maven and run tests with Postgresql
      - name: Build with Maven and run tests with PostgreSQL
        run: mvn --batch-mode -Dmicronaut.environments=test-postgres -Dtest='!life.qbic.db.mariadb.**' verify

      # build with maven and run tests with MariaDB
      - name: Build with Maven and run tests with MariaDB
        run: mvn --batch-mode -Dmicronaut.environments=test-mariadb -Dtest='!life.qbic.db.postgres.**' verify
