--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET SCHEMA 'public';

--
-- Name: project; Type: TABLE; Schema: public;
--

CREATE TABLE project (
                         id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
                         identifier character varying NOT NULL
);

--
-- Name: annotationsoftware; Type: TABLE; Schema: public;
--

CREATE TABLE annotationsoftware (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying,
    version character varying,
    doi character varying
);

--
-- Name: annotationsoftware_consequence; Type: TABLE; Schema: public;
--

CREATE TABLE annotationsoftware_consequence (
    annotationsoftware_id bigint NOT NULL,
    consequence_id bigint NOT NULL
);

--
-- Name: consequence; Type: TABLE; Schema: public;
--

CREATE TABLE consequence (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    allele character varying,
    codingchange character varying,
    transcriptid character varying,
    transcriptversion integer,
    type character varying,
    biotype character varying,
    canonical boolean,
    aachange character varying,
    cdnaposition character varying,
    cdsposition character varying,
    proteinposition character varying,
    proteinlength integer,
    cdnalength integer,
    cdslength integer,
    impact character varying,
    exon character varying,
    intron character varying,
    strand integer,
    genesymbol character varying,
    featuretype character varying,
    distance integer,
    warnings character varying
);

--
-- Name: ensembl; Type: TABLE; Schema: public;
--

CREATE TABLE ensembl (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    version integer,
    date character varying,
    referencegenome_id bigint
);

--
-- Name: ensembl_gene; Type: TABLE; Schema: public;
--

CREATE TABLE ensembl_gene (
    ensembl_id bigint NOT NULL,
    gene_id bigint NOT NULL
);

--
-- Name: entity; Type: TABLE; Schema: public;
-- id character varying NOT NULL,

CREATE TABLE entity (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier character varying,
    project_id bigint NOT NULL
);

--
-- Name: gene; Type: TABLE; Schema: public;
--

CREATE TABLE gene (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    symbol character varying,
    name character varying,
    biotype character varying,
    chr character varying,
    start bigint,
    "end" bigint,
    synonyms character varying[],
    geneid character varying,
    description character varying,
    strand character varying,
    version integer
);

--
-- Name: gene_consequence; Type: TABLE; Schema: public;
--

CREATE TABLE gene_consequence (
    consequence_id bigint NOT NULL,
    gene_id bigint NOT NULL
);

--
-- Name: genotype; Type: TABLE; Schema: public;
--

CREATE TABLE genotype (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    genotype character varying,
    readdepth integer,
    filter character varying,
    likelihoods character varying,
    genotypelikelihoods character varying,
    genotypelikelihoodshet character varying,
    posteriorprobs character varying,
    genotypequality integer,
    haplotypequalities character varying,
    phaseset character varying,
    phasingquality integer,
    alternateallelecounts character varying,
    mappingquality integer
);

--
-- Name: referencegenome; Type: TABLE; Schema: public;
--

CREATE TABLE referencegenome (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    source character varying,
    build character varying,
    version character varying
);

--
-- Name: referencegenome_variant; Type: TABLE; Schema: public;
--

CREATE TABLE referencegenome_variant (
    referencegenome_id bigint NOT NULL,
    variant_id bigint NOT NULL
);

--
-- Name: sample; Type: TABLE; Schema: public;
--

CREATE TABLE sample (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    identifier character varying,
    cancerentity character varying,
    entity_id bigint
);

--
-- Name: sample_variant; Type: TABLE; Schema: public;
--

CREATE TABLE sample_variant (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sample_id bigint,
    variant_id bigint,
    vcfinfo_id bigint,
    genotype_id bigint
);

--
-- Name: variant; Type: TABLE; Schema: public;
--

CREATE TABLE variant (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    chr character varying,
    start bigint,
    "end" bigint,
    ref character varying,
    obs character varying,
    somatic boolean,
    identifier character varying,
    databaseidentifier character varying
);

--
-- Name: variant_consequence; Type: TABLE; Schema: public;
--

CREATE TABLE variant_consequence (
    variant_id bigint NOT NULL,
    consequence_id bigint NOT NULL
);

--
-- Name: variantcaller; Type: TABLE; Schema: public;
--

CREATE TABLE variantcaller (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying,
    version character varying,
    doi character varying
);

--
-- Name: variantcaller_variant; Type: TABLE; Schema: public;
--

CREATE TABLE variantcaller_variant (
    variant_id bigint NOT NULL,
    variantcaller_id bigint NOT NULL
);

--
-- Name: vcfinfo; Type: TABLE; Schema: public;
--

CREATE TABLE vcfinfo (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ancestralallele character varying,
    allelecount character varying,
    allelefrequency character varying,
    numberalleles integer,
    basequality integer,
    cigar character varying,
    dbsnp boolean,
    hapmaptwo boolean,
    hapmapthree boolean,
    thousandgenomes boolean,
    combineddepth integer,
    endpos integer,
    rms float8,
    mqzero integer,
    strandbias integer,
    numbersamples integer,
    somatic boolean,
    validated boolean
);

--
-- Name: annotationsoftware annotationsoftware_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY annotationsoftware
    ADD CONSTRAINT annotationsoftware_pkey PRIMARY KEY (id);

--
-- Name: consequence consequence_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY consequence
    ADD CONSTRAINT consequence_pkey PRIMARY KEY (id);


--
-- Name: ensembl ensembl_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY ensembl
    ADD CONSTRAINT ensembl_pkey PRIMARY KEY (id);


--
-- Name: entity entity_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY entity
    ADD CONSTRAINT entity_pkey PRIMARY KEY (id);


--
-- Name: gene gene_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY gene
    ADD CONSTRAINT gene_pkey PRIMARY KEY (id);


--
-- Name: genotype genotype_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY genotype
    ADD CONSTRAINT genotype_pkey PRIMARY KEY (id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);


--
-- Name: referencegenome referencegenome_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY referencegenome
    ADD CONSTRAINT referencegenome_pkey PRIMARY KEY (id);


--
-- Name: sample sample_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY sample
    ADD CONSTRAINT sample_pkey PRIMARY KEY (id);


--
-- Name: variant variant_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY variant
    ADD CONSTRAINT variant_pkey PRIMARY KEY (id);


--
-- Name: variantcaller variantcaller_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY variantcaller
    ADD CONSTRAINT variantcaller_pkey PRIMARY KEY (id);


--
-- Name: vcfinfo vcfinfo_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY vcfinfo
    ADD CONSTRAINT vcfinfo_pkey PRIMARY KEY (id);


--
-- Name: as_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX as_unique ON annotationsoftware USING btree (name, version, doi);


--
-- Name: ascons_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX ascons_unique ON annotationsoftware_consequence USING btree (annotationsoftware_id, consequence_id);


--
-- Name: cons_gene_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX cons_gene_unique ON gene_consequence USING btree (gene_id, consequence_id);


--
-- Name: cons_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX cons_unique ON consequence USING btree (allele, codingchange, transcriptid, transcriptversion, type, biotype, canonical, aachange, cdnaposition, cdsposition, proteinposition, proteinlength, cdnalength, cdslength, impact, exon, intron, strand, genesymbol, featuretype, distance);


--
-- Name: ensembl_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX ensembl_unique ON ensembl USING btree (version, date, referencegenome_id);

--
-- Name: gene_unique; Type: INDEX; Schema: public;
--

CREATE INDEX gene_unique ON gene USING btree (geneid);


--
-- Name: genotype_unique; Type: INDEX; Schema: public;
--

CREATE INDEX genotype_unique ON genotype USING btree (genotype, readdepth, filter, likelihoods, genotypelikelihoods, genotypelikelihoodshet, posteriorprobs, genotypequality, haplotypequalities, phaseset, phasingquality, alternateallelecounts, mappingquality);


--
-- Name: idx_chromosome; Type: INDEX; Schema: public;
--

CREATE INDEX idx_chromosome ON variant USING btree (chr);


--
-- Name: idx_constype; Type: INDEX; Schema: public;
--

CREATE INDEX idx_constype ON consequence USING btree (type);


--
-- Name: idx_ensembl_id; Type: INDEX; Schema: public;
--

CREATE INDEX idx_ensembl_id ON ensembl_gene USING btree (ensembl_id);


--
-- Name: idx_entity_id; Type: INDEX; Schema: public;
--

CREATE INDEX idx_entity_id ON sample USING btree (entity_id);


--
-- Name: idx_gene_id; Type: INDEX; Schema: public;
--

CREATE INDEX idx_gene_id ON ensembl_gene USING btree (gene_id);


--
-- Name: idx_geneid; Type: INDEX; Schema: public;
--

CREATE INDEX idx_geneid ON gene USING btree (geneid);


--
-- Name: idx_genesymbol; Type: INDEX; Schema: public;
--

CREATE INDEX idx_genesymbol ON consequence USING btree (genesymbol);


--
-- Name: idx_rg; Type: INDEX; Schema: public;
--

CREATE INDEX idx_rg ON ensembl USING btree (referencegenome_id);


--
-- Name: idx_rg_build; Type: INDEX; Schema: public;
--

CREATE INDEX idx_rg_build ON referencegenome USING btree (build);


--
-- Name: idx_sample_id; Type: INDEX; Schema: public;
--

CREATE INDEX idx_sample_id ON sample USING btree (identifier);


--
-- Name: idx_sample_variant; Type: INDEX; Schema: public;
--

CREATE INDEX idx_sample_variant ON sample_variant USING btree (sample_id, variant_id);


--
-- Name: idx_start; Type: INDEX; Schema: public;
--

CREATE INDEX idx_start ON variant USING btree (start);


--
-- Name: idx_variant_sample; Type: INDEX; Schema: public;
--

CREATE INDEX idx_variant_sample ON sample_variant USING btree (variant_id, sample_id);


--
-- Name: rg_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX rg_unique ON referencegenome USING btree (source, build, version);


--
-- Name: sample_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX sample_unique ON sample USING btree (identifier, cancerentity, entity_id);

--
-- Name: project_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX project_unique ON project USING btree (identifier);

--
-- Name: entity_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX entity_unique ON entity USING btree (identifier, project_id);

--
-- Name: sample_variant_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX sample_variant_unique ON sample_variant USING btree (sample_id, variant_id, vcfinfo_id, genotype_id);


--
-- Name: variant_rg_unique; Type: INDEX; Schema: public;
--

-- CREATE UNIQUE INDEX variant_rg_unique ON referencegenome_variant USING btree (referencegenome_id, variant_id);


--
-- Name: variant_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX variant_unique ON variant USING btree (chr, start, "end", ref, obs, somatic, databaseidentifier);


--
-- Name: variant_vc_unique; Type: INDEX; Schema: public;
--

-- CREATE UNIQUE INDEX variant_vc_unique ON variantcaller_variant USING btree (variant_id, variantcaller_id);


--
-- Name: variantcaller_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX variantcaller_unique ON variantcaller USING btree (name, version, doi);


--
-- Name: vcfinfo_unique; Type: INDEX; Schema: public;
--

CREATE UNIQUE INDEX vcfinfo_unique ON vcfinfo USING btree (ancestralallele, allelecount, allelefrequency, numberalleles, basequality, cigar, dbsnp, hapmaptwo, hapmapthree, thousandgenomes, combineddepth, endpos, rms, mqzero, strandbias, numbersamples, somatic, validated);

-- CREATE UNIQUE INDEX variant_consequence_unique ON variant_consequence USING btree (variant_id, consequence_id);


--
-- Name: annotationsoftware_consequence annotationsoftware_consequence_annotationsoftware_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY annotationsoftware_consequence
    ADD CONSTRAINT annotationsoftware_consequence_annotationsoftware_id_fkey FOREIGN KEY (annotationsoftware_id) REFERENCES annotationsoftware(id) NOT VALID;


--
-- Name: annotationsoftware_consequence annotationsoftware_consequence_consequence_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY annotationsoftware_consequence
    ADD CONSTRAINT annotationsoftware_consequence_consequence_id_fkey FOREIGN KEY (consequence_id) REFERENCES consequence(id) NOT VALID;


--
-- Name: ensembl_gene ensembl_gene_ensembl_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY ensembl_gene
    ADD CONSTRAINT ensembl_gene_ensembl_id_fkey FOREIGN KEY (ensembl_id) REFERENCES ensembl(id) NOT VALID;


--
-- Name: ensembl_gene ensembl_gene_gene_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY ensembl_gene
    ADD CONSTRAINT ensembl_gene_gene_id_fkey FOREIGN KEY (gene_id) REFERENCES gene(id) NOT VALID;


--
-- Name: ensembl ensembl_referencegenome_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY ensembl
    ADD CONSTRAINT ensembl_referencegenome_id_fkey FOREIGN KEY (referencegenome_id) REFERENCES referencegenome(id) NOT VALID;


--
-- Name: entity entity_project_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY entity
    ADD CONSTRAINT entity_project_id_fkey FOREIGN KEY (project_id) REFERENCES project(id) NOT VALID;


--
-- Name: gene_consequence gene_consequence_consequence_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY gene_consequence
    ADD CONSTRAINT gene_consequence_consequence_id_fkey FOREIGN KEY (consequence_id) REFERENCES consequence(id) NOT VALID;


--
-- Name: gene_consequence gene_consequence_gene_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY gene_consequence
    ADD CONSTRAINT gene_consequence_gene_id_fkey FOREIGN KEY (gene_id) REFERENCES gene(id) NOT VALID;


--
-- Name: referencegenome_variant referencegenome_variant_referencegenome_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY referencegenome_variant
    ADD CONSTRAINT referencegenome_variant_referencegenome_id_fkey FOREIGN KEY (referencegenome_id) REFERENCES referencegenome(id) NOT VALID;


--
-- Name: referencegenome_variant referencegenome_variant_variant_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY referencegenome_variant
    ADD CONSTRAINT referencegenome_variant_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES variant(id) NOT VALID;


--
-- Name: sample sample_entity_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY sample
    ADD CONSTRAINT sample_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES entity(id) NOT VALID;


--
-- Name: sample_variant sample_variant_genotype_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY sample_variant
    ADD CONSTRAINT sample_variant_genotype_id_fkey FOREIGN KEY (genotype_id) REFERENCES genotype(id) NOT VALID;


--
-- Name: sample_variant sample_variant_sample_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY sample_variant
    ADD CONSTRAINT sample_variant_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES sample(id) NOT VALID;


--
-- Name: sample_variant sample_variant_variant_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY sample_variant
    ADD CONSTRAINT sample_variant_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES variant(id) NOT VALID;


--
-- Name: sample_variant sample_variant_vcfinfo_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY sample_variant
    ADD CONSTRAINT sample_variant_vcfinfo_id_fkey FOREIGN KEY (vcfinfo_id) REFERENCES vcfinfo(id) NOT VALID;


--
-- Name: variantcaller_variant variantcaller_variant_variant_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY variantcaller_variant
    ADD CONSTRAINT variantcaller_variant_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES variant(id) NOT VALID;

--
-- Name: variantcaller_variant variantcaller_variant_variantcaller_id_fkey; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY variantcaller_variant
    ADD CONSTRAINT variantcaller_variant_variantcaller_id_fkey FOREIGN KEY (variantcaller_id) REFERENCES variantcaller(id) NOT VALID;

ALTER TABLE ONLY variant_consequence
    ADD CONSTRAINT variant_consequence_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES variant(id) NOT VALID;

ALTER TABLE ONLY variant_consequence
    ADD CONSTRAINT variant_consequence_consequence_id_fkey FOREIGN KEY (consequence_id) REFERENCES consequence(id) NOT VALID;


--
-- PostgreSQL database dump complete
--
